// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package testing

import (
	"github.com/lehajam/grapi/pkg/cli"
	"github.com/lehajam/grapi/pkg/gencmd"
	"github.com/lehajam/grapi/pkg/grapicmd"
	"github.com/lehajam/grapi/pkg/protoc"
	"github.com/lehajam/grapi/pkg/svcgen"
)

// Injectors from wire.go:

func NewTestApp(command *gencmd.Command, wrapper protoc.Wrapper, ui cli.UI) (*svcgen.App, error) {
	ctx := gencmd.ProvideCtx(command)
	grapicmdCtx := gencmd.ProvideGrapiCtx(ctx)
	rootDir := grapicmd.ProvideRootDir(grapicmdCtx)
	config := grapicmd.ProvideProtocConfig(grapicmdCtx)
	grapicmdConfig := grapicmd.ProvideConfig(grapicmdCtx)
	builder := svcgen.ProvideParamsBuilder(rootDir, config, grapicmdConfig)
	app := &svcgen.App{
		ProtocWrapper: wrapper,
		ParamsBuilder: builder,
	}
	return app, nil
}
